name : Lint Test And Deploy Project On Push
on: [ push,workflow_dispatch ]
jobs:
  mytest:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run:  npm ci
      - name: Lint Code
        run:  npm run lint
      - name: Run Tests
        run:  npm run test
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."
